;[application]
# relief in ['flat', 'raised', 'sunken', 'solid', 'ridge', 'groove']
; Attention ne pas mettre de commentaire en fin de ligne car ils sont récupérés
; avec la valeur qui suit le signe '='

[infoframe]

borderwidth = 2
background = yellow
disabled_background = light grey
relief = groove
filename_width = 50

[playercontrol]

borderwidth = 2
background = red
relief = groove

[codingframework]

borderwidth = 2
background = cyan 
disabled_background = light gray 
relief = groove 

panel_max = 5

;[newcode]
